fail_on_violations: true

flake8:
  enabled: true
  config_file: .flake8.ini

scss:
  enabled: true
  config_file: frontend/.stylelintrc.yml

eslint:
  enabled: true
  config_file: frontend/.eslintrc
